plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'games.moisoni.google_inapp_billing'
    compileSdkVersion 37

    defaultConfig {
        applicationId "games.moisoni.google_inapp_billing"
        minSdkVersion 23
        targetSdkVersion 37

        versionCode 11
        versionName "v2.1.0"

        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.appcompat.v180
    implementation libs.material.v1140
    implementation libs.constraintlayout
    implementation libs.kotlin.stdlib
    implementation(platform(libs.kotlin.bom))

    implementation libs.sdp.android
    implementation libs.ssp.android

    implementation libs.bounceview.android

    implementation project(':google-iab')
}